UPDATE `pvp_reward` SET `BaseLevel` = '885' WHERE `Type` = '0'; 
UPDATE `pvp_reward` SET `BaseLevel` = '885' WHERE `Type` = '1'; 
UPDATE `pvp_reward` SET `BaseLevel` = '885' WHERE `Type` = '2'; 
UPDATE `pvp_reward` SET `BaseLevel` = '885' WHERE `Type` = '3'; 
UPDATE `pvp_reward` SET `BaseLevel` = '885' WHERE `Type` = '4'; 
UPDATE `pvp_reward` SET `BaseLevel` = '885' WHERE `Type` = '6'; 
UPDATE `pvp_reward` SET `ElitLevel` = '910' WHERE `Type` = '2'; 
UPDATE `pvp_reward` SET `ElitLevel` = '910' WHERE `Type` = '3'; 
UPDATE `pvp_reward` SET `ElitLevel` = '910' WHERE `Type` = '4'; 

INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemLevelSelectorID`, `ItemContext`, `BonusTreeID`, `VerifiedBuild`) VALUES ('1615', '134', '25', '463', '26124');
INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemLevelSelectorID`, `ItemContext`, `BonusTreeID`, `VerifiedBuild`) VALUES ('1704', '135', '26', '463', '26124');
INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemLevelSelectorID`, `ItemContext`, `BonusTreeID`, `VerifiedBuild`) VALUES ('1705', '136', '27', '463', '26124');
INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemLevelSelectorID`, `ItemContext`, `BonusTreeID`, `VerifiedBuild`) VALUES ('1706', '60', '28', '463', '26124');
INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemLevelSelectorID`, `ItemContext`, `BonusTreeID`, `VerifiedBuild`) VALUES ('1708', '61', '29', '463', '26124');
INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemLevelSelectorID`, `ItemContext`, `BonusTreeID`, `VerifiedBuild`) VALUES ('1722', '62', '30', '463', '26124');
INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemBonusListID`, `BonusTreeID`, `VerifiedBuild`) VALUES ('2586', '3530', '645', '26124');
INSERT INTO `item_bonus_tree_node` (`ID`, `ChildItemBonusListID`, `BonusTreeID`, `VerifiedBuild`) VALUES ('4177', '3570', '608', '26124');

INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('12', '845', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('13', '825', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('17', '865', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('18', '870', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('40', '870', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('41', '870', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('42', '870', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('43', '875', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('44', '875', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('45', '875', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('46', '880', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('47', '880', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('48', '885', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('49', '885', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('50', '890', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('113', '895', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('114', '895', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('128', '900', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('129', '905', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('130', '910', '2', '26124');
INSERT INTO `item_level_selector` (`ID`, `ItemLevel`, `ItemLevelSelectorQualitySetID`, `VerifiedBuild`) VALUES ('251', '880', '2', '26124');

-- Use this when open Argus
-- TRUNCATE `item_bonus_tree_node`;
-- TRUNCATE `item_level_selector`

-- UPDATE `pvp_reward` SET `BaseLevel` = '915' WHERE `Type` = '0'; 
-- UPDATE `pvp_reward` SET `BaseLevel` = '915' WHERE `Type` = '1'; 
-- UPDATE `pvp_reward` SET `BaseLevel` = '915' WHERE `Type` = '2'; 
-- UPDATE `pvp_reward` SET `BaseLevel` = '915' WHERE `Type` = '3'; 
-- UPDATE `pvp_reward` SET `BaseLevel` = '915' WHERE `Type` = '4'; 
-- UPDATE `pvp_reward` SET `BaseLevel` = '915' WHERE `Type` = '6'; 
-- UPDATE `pvp_reward` SET `ElitLevel` = '940' WHERE `Type` = '2'; 
-- UPDATE `pvp_reward` SET `ElitLevel` = '940' WHERE `Type` = '3'; 
-- UPDATE `pvp_reward` SET `ElitLevel` = '940' WHERE `Type` = '4'; 

-- Char update
ALTER TABLE `characters` ADD `inventorySlots` tinyint(3) unsigned NOT NULL DEFAULT '16' AFTER `horn`;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=187 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=186 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=185 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=184 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=183 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=182 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=181 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=180 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=179 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=178 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=177 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=176 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=175 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=174 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=173 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=172 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=171 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=170 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=169 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=168 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=167 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=166 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=165 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=164 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=163 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=162 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=161 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=160 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=159 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=158 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=157 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=156 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=155 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=154 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=153 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=152 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=151 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=150 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=149 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=148 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=147 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=146 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=145 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=144 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=143 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=142 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=141 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=140 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=139 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=138 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=137 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=136 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=135 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=134 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=133 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=132 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=131 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=130 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=129 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=128 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=127 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=126 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=125 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=124 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=123 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=122 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=121 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=120 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=119 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=118 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=117 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=116 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=115 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=114 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=113 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=112 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=111 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=110 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=109 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=108 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=107 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=106 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=105 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=104 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=103 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=102 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=101 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=100 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=99 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=98 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=97 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=96 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=95 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=94 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=93 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=92 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=91 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=90 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=89 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=88 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=87 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=86 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=85 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=84 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=83 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=82 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=81 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=80 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=79 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=78 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=77 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=76 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=75 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=74 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=73 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=72 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=71 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=70 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=69 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=68 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=67 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=66 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=65 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=64 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=63 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=62 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=61 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=60 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=59 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=58 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=57 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=56 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=55 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=54 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=53 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=52 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=51 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=50 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=49 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=48 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=47 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=46 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=45 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=44 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=43 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=42 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=41 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=40 AND `bag`=0;
UPDATE `character_inventory` SET `slot`=`slot`+8 WHERE `slot`=39 AND `bag`=0;
UPDATE characters SET at_login = at_login | '22';
RENAME TABLE `char_army_training_info` TO `character_army_training_info`;
TRUNCATE `character_army_training_info`;
UPDATE character_brackets_info SET oldRating = rating, oldBest = best, oldMmr = mmr, oldGames = games, oldWins = wins;
UPDATE character_brackets_info SET rating = 0, best = 0, mmr = 1500, games = 0, wins = 0;
TRUNCATE `challenge_oplote_loot`;
