CREATE TABLE `character_template_quest` (
  `TemplateID` INT(10) NOT NULL DEFAULT '38',
  `ClassID` TINYINT(3) NOT NULL DEFAULT '0',
  `QuestID` INT(10) NOT NULL DEFAULT '0',
  `RaceID` TINYINT(3) NOT NULL DEFAULT '0'
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
