ALTER TABLE `battle_pet_species`   
  CHANGE `Description` `Description` TEXT CHARSET utf8 COLLATE utf8_general_ci NULL  AFTER `spellId`,
  CHANGE `SourceText` `SourceText` TEXT CHARSET utf8 COLLATE utf8_general_ci NULL  AFTER `Description`,
  CHANGE `flags` `flags` SMALLINT(6) UNSIGNED DEFAULT 0  NOT NULL  AFTER `SourceText`,
  CHANGE `petType` `petType` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `source` `source` TINYINT(3) DEFAULT 0  NOT NULL;

ALTER TABLE `battle_pet_species_state`   
  CHANGE `Value` `Value` INT(11) DEFAULT 0  NOT NULL  AFTER `ID`,
  CHANGE `SpeciesID` `SpeciesID` SMALLINT(6) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `State` `State` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL;

ALTER TABLE `battle_pet_state`   
  CHANGE `stateName` `stateName` TEXT CHARSET utf8 COLLATE utf8_general_ci NULL  AFTER `ID`,
  CHANGE `flags` `flags` SMALLINT(6) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `unk` `unk` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL  AFTER `flags`;

ALTER TABLE `battle_pet_species_x_ability`   
  CHANGE `speciesID` `speciesID` SMALLINT(6) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `abilityID` `abilityID` SMALLINT(6) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `requiredLevel` `requiredLevel` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `rank` `rank` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL;

ALTER TABLE `barber_shop_style`   
  DROP COLUMN `Tato`, 
  CHANGE `Type` `Type` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL  AFTER `CostMultiplier`;

ALTER TABLE `battlemaster_list`   
  DROP COLUMN `NameLang`, 
  ADD COLUMN `NameLang` TEXT NULL AFTER `ID`,
  ADD COLUMN `IconFileDataID` INT(10) DEFAULT 0  NOT NULL AFTER `NameLang`,
  ADD COLUMN `GametypeLang` TEXT NULL AFTER `IconFileDataID`,
  CHANGE `MapID1` `MapID1` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID2` `MapID2` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID3` `MapID3` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID4` `MapID4` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID5` `MapID5` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID6` `MapID6` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID7` `MapID7` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID8` `MapID8` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID9` `MapID9` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID10` `MapID10` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID11` `MapID11` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID12` `MapID12` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID13` `MapID13` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID14` `MapID14` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID15` `MapID15` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `MapID16` `MapID16` SMALLINT(6) DEFAULT 0  NOT NULL,
  CHANGE `HolidayWorldState` `HolidayWorldState` SMALLINT(6) UNSIGNED DEFAULT 0  NOT NULL  AFTER `MapID16`,
  ADD COLUMN `CritreriaID` SMALLINT(6) DEFAULT 0  NULL AFTER `HolidayWorldState`,
  CHANGE `InstanceType` `InstanceType` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  ADD COLUMN `GroupsAllowed` TINYINT(3) NULL AFTER `InstanceType`,
  CHANGE `MaxGroupSize` `MaxGroupSize` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `Minlevel` `Minlevel` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `Maxlevel` `Maxlevel` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `RatedPlayers` `RatedPlayers` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `MinPlayers` `MinPlayers` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `MaxPlayers` `MaxPlayers` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `Flags` `Flags` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL;

CREATE TABLE `battlemaster_list_locale` (
  `ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `locale` VARCHAR(4) NOT NULL,
  `NameLang` TEXT,
  `GametypeLang` TEXT,
  `VerifiedBuild` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`,`locale`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;

ALTER TABLE `battle_pet_breed_quality`   
  CHANGE `qualityModifier` `qualityModifier` FLOAT DEFAULT 0  NOT NULL  AFTER `ID`,
  CHANGE `quality` `quality` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL;

ALTER TABLE `battle_pet_breed_state`   
  CHANGE `stateModifier` `stateModifier` SMALLINT(6) DEFAULT 0  NOT NULL  AFTER `ID`,
  CHANGE `breedID` `breedID` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL,
  CHANGE `stateID` `stateID` TINYINT(3) UNSIGNED DEFAULT 0  NOT NULL;
