CREATE TABLE `conversationline`(  
  `ID` INT(10) NOT NULL DEFAULT 0,
  `tesxID` INT(10) NOT NULL DEFAULT 0,
  `duration` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `unk` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `nextID` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `unk1` TINYINT(3) NOT NULL DEFAULT 0,
  `unk2` TINYINT(3) NOT NULL DEFAULT 0,
  `unk3` TINYINT(3) NOT NULL DEFAULT 0,
  `unk4` TINYINT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM CHARSET=utf8 COLLATE=utf8_general_ci;
