CREATE TABLE `quest_v2_cli_task`(  
  `ID` INT(10) NOT NULL DEFAULT 0,
  `Flags` INT(10) NOT NULL DEFAULT 0,
  `Unk` INT(10) NOT NULL DEFAULT 0,
  `Name` TEXT,
  `Name1` TEXT,
  `Unk2` INT(10) NOT NULL DEFAULT 0,
  `Unk3` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk4` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk5` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk6` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk7` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk8` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk9` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk10` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `Unk11` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk12` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk13` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk14` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk15` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk16` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk17` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk18` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk19` TINYINT(3) NOT NULL DEFAULT 0,
  `Unk20` TINYINT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM CHARSET=utf8 COLLATE=utf8_general_ci;

DROP TABLE IF EXISTS `quest_v2_cli_task_locale`;
CREATE TABLE `quest_v2_cli_task_locale` (
  `ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `locale` VARCHAR(4) NOT NULL,
  `Name_lang` TEXT,
  `Name1_lang` TEXT,
  `VerifiedBuild` SMALLINT(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`,`locale`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
