CREATE TABLE `area_assignment`(  
  `ID` INT(10) NOT NULL DEFAULT 0,
  `MapID` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `AreaID` MEDIUMINT(6) NOT NULL DEFAULT 0,
  `cellX` TINYINT(3) NOT NULL DEFAULT 0,
  `cellY` TINYINT(3) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=MYISAM CHARSET=utf8 COLLATE=utf8_general_ci;
