DROP TABLE IF EXISTS `spell_item_enchantment`;
CREATE TABLE `spell_item_enchantment` (
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `EffectSpellID1` int(10) unsigned NOT NULL DEFAULT '0',
  `EffectSpellID2` int(10) unsigned NOT NULL DEFAULT '0',
  `EffectSpellID3` int(10) unsigned NOT NULL DEFAULT '0',
  `Name` text,
  `EffectScalingPoints1` float NOT NULL DEFAULT '0',
  `EffectScalingPoints2` float NOT NULL DEFAULT '0',
  `EffectScalingPoints3` float NOT NULL DEFAULT '0',
  `TransmogCost` int(10) unsigned NOT NULL DEFAULT '0',
  `TextureFileDataID` int(10) unsigned NOT NULL DEFAULT '0',
  `EffectPointsMin1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `EffectPointsMin2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `EffectPointsMin3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ItemVisual` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Flags` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RequiredSkillID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RequiredSkillRank` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ItemLevel` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Charges` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Effect1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Effect2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Effect3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ConditionID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MinLevel` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MaxLevel` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ScalingClass` tinyint(4) NOT NULL DEFAULT '0',
  `ScalingClassRestricted` tinyint(4) NOT NULL DEFAULT '0',
  `PlayerConditionID` int(10) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `spell_item_enchantment_condition`;
CREATE TABLE `spell_item_enchantment_condition` (
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `LTOperandType1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LTOperandType2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LTOperandType3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LTOperandType4` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LTOperandType5` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Operator1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Operator2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Operator3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Operator4` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Operator5` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperandType1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperandType2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperandType3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperandType4` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperandType5` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperand1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperand2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperand3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperand4` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RTOperand5` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Logic1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Logic2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Logic3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Logic4` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Logic5` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LTOperand1` int(10) unsigned NOT NULL DEFAULT '0',
  `LTOperand2` int(10) unsigned NOT NULL DEFAULT '0',
  `LTOperand3` int(10) unsigned NOT NULL DEFAULT '0',
  `LTOperand4` int(10) unsigned NOT NULL DEFAULT '0',
  `LTOperand5` int(10) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
