DROP TABLE `item_sparse`;
DROP TABLE `item_sparse_locale`;

DELETE FROM `map` WHERE `ID` = '616';
DELETE FROM `map` WHERE `ID` = '1616';
DELETE FROM `map` WHERE `ID` = '1673';
DELETE FROM `map` WHERE `ID` = '1684';
DELETE FROM `map` WHERE `ID` = '1698';
DELETE FROM `map` WHERE `ID` = '1702';
DELETE FROM `map` WHERE `ID` = '1703';
DELETE FROM `map` WHERE `ID` = '1710';

DELETE FROM `taxi_nodes` WHERE `ID` = '1620';
DELETE FROM `taxi_nodes` WHERE `ID` = '1621';
DELETE FROM `taxi_nodes` WHERE `ID` = '1643';
DELETE FROM `taxi_nodes` WHERE `ID` = '1644';
DELETE FROM `taxi_nodes` WHERE `ID` = '1645';
DELETE FROM `taxi_nodes` WHERE `ID` = '1646';
DELETE FROM `taxi_nodes` WHERE `ID` = '1647';
DELETE FROM `taxi_nodes` WHERE `ID` = '1648';

TRUNCATE `anim_kit`;
TRUNCATE `area_group_member`;
TRUNCATE `artifact_power_rank`;
TRUNCATE `char_titles`;
TRUNCATE `char_titles_locale`;
TRUNCATE `chr_specialization`;
TRUNCATE `creature_model_data`;
TRUNCATE `criteria`;
TRUNCATE `criteria_tree`;
TRUNCATE `currency_types`;
TRUNCATE `curve_point`;
TRUNCATE `faction`;
TRUNCATE `hotfix_data`;
TRUNCATE `item_bonus`;
TRUNCATE `item_bonus_tree_node`;
TRUNCATE `item_level_selector`;
TRUNCATE `item_spec_override`;
TRUNCATE `item_x_bonus_tree`;
TRUNCATE `modifier_tree`;
TRUNCATE `override_spell_data`;
TRUNCATE `phase`;
TRUNCATE `quest_v2`;
TRUNCATE `scaling_stat_distribution`;
TRUNCATE `scenario_step`;
TRUNCATE `specialization_spells`;
TRUNCATE `spell`;
TRUNCATE `spell_aura_options`;
TRUNCATE `spell_aura_restrictions`;
TRUNCATE `spell_casting_requirements`;
TRUNCATE `spell_categories`;
TRUNCATE `spell_category`;
TRUNCATE `spell_class_options`;
TRUNCATE `spell_cooldowns`;
TRUNCATE `spell_effect`;
TRUNCATE `spell_focus_object`;
TRUNCATE `spell_interrupts`;
TRUNCATE `spell_locale`;
TRUNCATE `spell_misc`;
TRUNCATE `spell_misc_difficulty`;
TRUNCATE `spell_procs_per_minute_mod`;
TRUNCATE `spell_reagents`;
TRUNCATE `spell_scaling`;
TRUNCATE `spell_target_restrictions`;
TRUNCATE `spell_x_spell_visual`;
TRUNCATE `vehicle`;
TRUNCATE `world_safe_locs`
