DROP TABLE IF EXISTS `adventure_journal`;
CREATE TABLE `adventure_journal` (
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `Title` text,
  `Description` text,
  `ButtonText` text,
  `Flags` int(10) unsigned NOT NULL DEFAULT '0',
  `Flags2` int(10) unsigned NOT NULL DEFAULT '0',
  `Unk3` text,
  `ObjectiveText` text,
  `MapID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `PlayedConditionIDUnk` smallint(5) unsigned NOT NULL DEFAULT '0',
  `QuestID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `PlayedConditionIDUnk21` smallint(5) unsigned NOT NULL DEFAULT '0',
  `PlayedConditionIDUnk22` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Unk6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Unk7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Unk9` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk10` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk11` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk12` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk13` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk141` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk142` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk15` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Unk16` int(10) unsigned NOT NULL DEFAULT '0',
  `Unk17` int(10) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `adventure_journal_locale`;
CREATE TABLE `adventure_journal_locale` (
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `locale` varchar(4) NOT NULL,
  `Title_lang` text,
  `Description_lang` text,
  `ButtonText_lang` text,
  `Unk3_lang` text,
  `ObjectiveText_lang` text,
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`,`locale`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `quest_v2_cli_task`;
CREATE TABLE `quest_v2_cli_task` (
  `Flags` int(11) NOT NULL DEFAULT '0',
  `Name` text,
  `Name1` text,
  `requestAura` int(10) unsigned NOT NULL DEFAULT '0',
  `UniqueBitFlag` smallint(5) unsigned NOT NULL DEFAULT '0',
  `PlayerConditionID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Unk5` smallint(6) NOT NULL DEFAULT '0',
  `requestQuest1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `requestQuest2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `requestQuest3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `SkillID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `WorldStateExpressionID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `unk13` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `unk14` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `unk15` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `unk16` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MaxLevel` tinyint(4) NOT NULL DEFAULT '0',
  `unk18` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `unk19` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MinLevel` tinyint(4) NOT NULL DEFAULT '0',
  `SkillValue` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `unk21` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `unk23` int(10) unsigned NOT NULL DEFAULT '0',
  `QuestInfoID` int(10) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `char_shipment_container`;
CREATE TABLE `char_shipment_container` (
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `Name` text,
  `Description` text,
  `ActiveVisualID` int(10) unsigned NOT NULL DEFAULT '0',
  `Unk720` smallint(5) unsigned NOT NULL DEFAULT '0',
  `DisplayID_Unk` smallint(5) unsigned NOT NULL DEFAULT '0',
  `DisplayID_A` smallint(5) unsigned NOT NULL DEFAULT '0',
  `DisplayID_H` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Unk_Display` smallint(5) unsigned NOT NULL DEFAULT '0',
  `unk8` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Flags` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `BuildingType` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `GarrTypeID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MaxShipments` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `enotherID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `fractionType` tinyint(4) NOT NULL DEFAULT '0',
  `unk16` int(10) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `garr_building`;
CREATE TABLE `garr_building` (
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `HordeGameObjectID` int(10) unsigned NOT NULL DEFAULT '0',
  `AllianceGameObjectID` int(10) unsigned NOT NULL DEFAULT '0',
  `NameAlliance` text,
  `NameHorde` text,
  `Description` text,
  `Tooltip` text,
  `IconFileDataID` int(10) unsigned NOT NULL DEFAULT '0',
  `CostCurrencyID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `HordeTexPrefixKitID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `AllianceTexPrefixKitID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `AllianceActivationScenePackageID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `HordeActivationScenePackageID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `FollowerRequiredGarrAbilityID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `FollowerGarrAbilityEffectID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `CostMoney` smallint(6) NOT NULL DEFAULT '0',
  `unk16` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Type` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Flags` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MaxShipments` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `GarrTypeID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `BuildDuration` int(10) unsigned NOT NULL DEFAULT '0',
  `CostCurrencyAmount` int(11) NOT NULL DEFAULT '0',
  `BonusAmount` int(10) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `garr_mission`;
CREATE TABLE `garr_mission` (
  `MissionDuration` int(10) unsigned NOT NULL DEFAULT '0',
  `OfferDuration` int(10) unsigned NOT NULL DEFAULT '0',
  `Name` text,
  `Description` text,
  `Location` text,
  `unk7` float NOT NULL DEFAULT '0',
  `unk8` float NOT NULL DEFAULT '0',
  `unk9` float NOT NULL DEFAULT '0',
  `unk10` float NOT NULL DEFAULT '0',
  `RequiredItemLevel` smallint(5) unsigned NOT NULL DEFAULT '0',
  `LocPrefixID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RewCurrencyID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `RequiredLevel` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `GarrMechanicTypeID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `RequiredFollowersCount` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Category` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `MissionType` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `FollowerType` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `BaseBonusChance` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LostChance` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `GarrTypeID` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `ID` int(10) unsigned NOT NULL DEFAULT '0',
  `TravelTime` int(10) unsigned NOT NULL DEFAULT '0',
  `CriteriaID` int(10) unsigned NOT NULL DEFAULT '0',
  `Unk3` int(10) unsigned NOT NULL DEFAULT '0',
  `CurrencyCost` int(10) unsigned NOT NULL DEFAULT '0',
  `Flags` int(10) unsigned NOT NULL DEFAULT '0',
  `RewardFollowerExperience` int(10) unsigned NOT NULL DEFAULT '0',
  `ZoneID` int(10) unsigned NOT NULL DEFAULT '0',
  `unk30` int(10) unsigned NOT NULL DEFAULT '0',
  `unk16` int(10) unsigned NOT NULL DEFAULT '0',
  `VerifiedBuild` smallint(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
