/* Molten core Firelord mob correction to spells */
UPDATE `world`.`smart_scripts` SET `event_flags` = '0', `target_type` = '2' WHERE (`entryorguid` = '11668') and (`source_type` = '0') and (`id` = '0') and (`link` = '0');
UPDATE `world`.`smart_scripts` SET `event_flags` = '0', `target_type` = '2' WHERE (`entryorguid` = '11668') and (`source_type` = '0') and (`id` = '1') and (`link` = '0');

/* Zul Aman Amni Lynx correction to spells */
UPDATE `world`.`smart_scripts` SET `link` = '1' WHERE (`entryorguid` = '24043') and (`source_type` = '0') and (`id` = '0') and (`link` = '0');
INSERT INTO `world`.`smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('24043', '0', '1', '0', '11', '0', '100', '1', '0', '0', '1000', '1000', '11', '42866', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Amani Lynx - On Respawn - Cast Stealth');
INSERT INTO `world`.`smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('24043', '0', '2', '0', '4', '0', '100', '0', '0', '0', '0', '0', '28', '42866', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Amani Lynx - On Aggro - Remove Aura Stealth');
INSERT INTO `world`.`smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('24043', '0', '3', '0', '0', '0', '100', '0', '5000', '5000', '35000', '35000', '11', '43357', '0', '0', '0', '0', '0', '2', '0', '0', '0', '0', '0', '0', '0', 'Amani Lynx - In Combat - Cast Feral Swipe');
