ALTER TABLE `character_battleground_random`   
  ADD COLUMN `bg` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL AFTER `guid`,
  ADD COLUMN `rbg` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL AFTER `bg`,
  ADD COLUMN `skirmish` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL AFTER `rbg`,
  ADD COLUMN `arena` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL AFTER `skirmish`;
